---
title: "基本描述性統計分析"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(dplyr)
library(maps)
youtuber = readRDS("../20180319/20180319_files/youtuber.rds")
youtuber = youtuber %>%
  mutate(
    UPLOADS = as.numeric(gsub(",", "", UPLOADS)),
    SUBSCRIBERS = as.numeric(gsub(",", "", SUBSCRIBERS)),
    VIEWS = as.numeric(gsub(",", "", VIEWS))
  ) %>%
  filter(
    UPLOADS > 0,
    SUBSCRIBERS > 0,
    VIEWS > 0,
    COUNTRY != "",
    TYPE != ""
  )
iso = iso3166 %>%
  select(a2, ISOname, mapname) %>%
  distinct(a2, .keep_all=TRUE)
youtuber = youtuber %>%
  left_join(iso, by=c("COUNTRY"="a2"))
```

## 資料整理(續)

### 儲存最終資料

```{r, warning=FALSE, message=FALSE}
## 透過計算字元數的方式僅擷取最後四碼年份
youtuber = youtuber %>%
  mutate(n_char = nchar(as.character(CREATED))) %>%
  mutate(YEAR = as.numeric(substr(CREATED, n_char-3, n_char)))

## 儲存整理完畢的資料，以後就可以直接讀取使用
saveRDS(youtuber, "20180326_files/youtuber.rds")

## 檢視前幾筆資料內容
head(youtuber)
```


## 描述性統計量

### 數值資料

```{r, warning=FALSE, message=FALSE}
## 加總
sum(youtuber$UPLOADS)

## 最大值
max(youtuber$SUBSCRIBERS)

## 最小值
min(youtuber$SUBSCRIBERS)

## 平均數
mean(youtuber$VIEWS)

## 中位數
median(youtuber$VIEWS)

## 分位數
quantile(youtuber$VIEWS, probs=0.9)
```


### 類別資料

```{r, warning=FALSE, message=FALSE}
## 次數彙整
tab = table(youtuber$TYPE)
tab

## 將 table 計算出來的次數轉換為比例
prop.table(tab)

## 雙變數列聯表
table(youtuber$TYPE, youtuber$YEAR)
```
